packages:
  - '.'

allowBuilds:
  core-js: true
  esbuild: true
  "@ffmpeg-installer/linux-x64": true

overrides:
  buffer: 6.0.3
  tough-cookie: ^5.1.2

onlyBuiltDependencies:
  - sqlite3
  - "@ffmpeg-installer/linux-x64"
  - esbuild

minimumReleaseAge: 0
